In [18]:
import pyodbc
import pandas
connection = pyodbc.connect('Driver={SQL Server};'
                                'Server=69.65.19.13;'
                                'Database=CaptainU;'
                                'uid=GenUser1;pwd=g3nP@ssw0rd#3')
sql="select * from [dbo].[MSG_MasterTable_RFM]"
data=pandas.read_sql(sql,connection,index_col=None, coerce_float=True, params=None, parse_dates=None, columns=None, chunksize=None)

In [1]:
%matplotlib inline
import pandas as pd
from ipywidgets import widgets
from IPython.display import display
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import tree
import sklearn.metrics as metrics
import pydotplus 
from IPython.display import Image
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from IPython.display import Image
import pydotplus 
from sklearn import preprocessing

In [6]:
data1.to_csv('training.csv', sep='\t', encoding='utf-8')

In [20]:
data['new']=data.groupby(['Athlete'],axis=0).Hits.cumsum()

In [21]:
pandas.set_option('display.max_columns', None)
print(data.head())

   Athlete  Subscription     Month gender     sport SegmentName  Duration  \
0   215018             0  Jan-2012      F  softball        None       NaN
1   215018             0  Feb-2012      F  softball        None       NaN
2   215018             0  Mar-2012      F  softball        None       NaN
3   215018             0  Apr-2012      F  softball        None       NaN
4   215018             0  May-2012      F  softball        None       NaN

   EventsAttended  EventsAttended_Frequency EventsAttended_LastDate  \
0               0                         0                    None
1               0                         0                    None
2               0                         0                    None
3               0                         0                    None
4               0                         0                    None

   EventsAttended_Recency  Hits  Hits_Frequency Hits_LastDate  Hits_Recency  \
0                     NaN     0               0          None           NaN
1                     NaN     0               0          None           NaN
2                     NaN     0               0          None           NaN
3                     NaN     0               0          None           NaN
4                     NaN     0               0          None           NaN

   Hprofileview  Hcoachimport  Hmessage  Hsearchhit  HNULL  Hcoacheval  \
0             0             0         0           0      0           0
1             0             0         0           0      0           0
2             0             0         0           0      0           0
3             0             0         0           0      0           0
4             0             0         0           0      0           0

   Hvideoview  Hemailopen  Emails  Emails_Frequency Emails_LastDate  \
0           0           0       0                 0            None
1           0           0       0                 0            None
2           0           0       0                 0            None
3           0           0       0                 0            None
4           0           0       0                 0            None

  Emails_Recency  EAthlete newsletter  Eathlete_new  \
0           None                    0             0
1           None                    0             0
2           None                    0             0
3           None                    0             0
4           None                    0             0

   Eathlete_new_info_request  ECCNote  ECCNote_camp  \
0                          0        0             0
1                          0        0             0
2                          0        0             0
3                          0        0             0
4                          0        0             0

   Ecoach_list_known_updated  ECoachEmailOpen  ECoachEval  ECoachImport  \
0                          0                0           0             0
1                          0                0           0             0
2                          0                0           0             0
3                          0                0           0             0
4                          0                0           0             0

   ECoachSearchHit  ECoachVideoViewHit  ECoachVisit  \
0                0                   0            0
1                0                   0            0
2                0                   0            0
3                0                   0            0
4                0                   0            0

   Ecolleges_going_to_the_event  Efailed_subscription  \
0                             0                     0
1                             0                     0
2                             0                     0
3                             0                     0
4                             0                     0

   Ehighlight_video__regathlete_11  Ehighlight_video__regathlete_2  \
0                                0                               0
1                                0                               0
2                                0                               0
3                                0                               0
4                                0                               0

   Ehighlight_video__regathlete_4  EEmailsDigest  Eparent_new  \
0                               0              0            0
1                               0              0            0
2                               0              0            0
3                               0              0            0
4                               0              0            0

   Eparent_welcome  Epost_event_email  Esms_update  CollegeProspects  \
0                0                  0            0                 0
1                0                  0            0                 0
2                0                  0            0                 0
3                0                  0            0                 0
4                0                  0            0                 0

   CollegeProspects_Frequency CollegeProspects_LastDate  \
0                           0                      None
1                           0                      None
2                           0                      None
3                           0                      None
4                           0                      None

   CollegeProspects_Recency  MessagesReceived  MessagesReceived_Frequency  \
0                       NaN                 0                           0
1                       NaN                 0                           0
2                       NaN                 0                           0
3                       NaN                 0                           0
4                       NaN                 0                           0

  MessagesReceived_LastDate  MessagesReceived_Recency  MessagesSent  \
0                      None                       NaN             0
1                      None                       NaN             0
2                      None                       NaN             0
3                      None                       NaN             0
4                      None                       NaN             0

   MessagesSent_Frequency MessagesSent_LastDate  MessagesSent_Recency  \
0                       0                  None                   NaN
1                       0                  None                   NaN
2                       0                  None                   NaN
3                       0                  None                   NaN
4                       0                  None                   NaN

   CaptainU_CHURN  MSG_CHURN  Made_Team?  DateNum  NumYear  NumMonth  \
0               0          0           0    40907     2012         1
1               0          0           0    40938     2012         2
2               0          0           0    40967     2012         3
3               0          0           0    40998     2012         4
4               0          0           0    41028     2012         5

   Subscriber?  monthly_price  Subscriptions_BOM  Subscription_Started  \
0            0            0.0                  0                     0
1            0            0.0                  0                     0
2            0            0.0                  0                     0
3            0            0.0                  0                     0
4            0            0.0                  0                     0

   subscription_Ended  Subscriptions_EOM  RecencyNow  RecencyStat  \
0                   0                  0        1734            0
1                   0                  0        1703            0
2                   0                  0        1674            0
3                   0                  0        1643            0
4                   0                  0        1613            0

   AthleteRecordNumber created_at updated_at status  ID  AthleteSub  new
0                    1       None       None   None   1           0    0
1                    2       None       None   None   2           0    0
2                    3       None       None   None   3           0    0
3                    4       None       None   None   4           0    0
4                    5       None       None   None   5           0    0

In [2]:
training = pd.read_csv('data/training.csv',encoding='utf-8')

In [50]:
onemchurn = pd.read_csv('data/one_month_churn.csv',encoding='utf-8')

In [55]:
onemchurn.head(15)

,Unnamed: 0,Unnamed: 0.1,Athlete,Subscription,Month,gender,sport,SegmentName,Duration,EventsAttended,...,RecencyStat,AthleteRecordNumber,created_at,updated_at,status,ID,AthleteSub,CaptainU_CHURN,MSG_CHURN,TMChurn
3188,3188,3188,220000,247241,2012-01-01,F,volleyball,NaN,83,0,...,0,1,2012-01-25 19:35:00,2012-04-17 22:15:00,NaN,5546,2200000,0,0,0
1322,1322,1322,218037,245146,2012-01-01,F,lacrosse,NaN,15,1,...,40919,1,2012-01-15 01:32:00,2012-01-30 22:37:00,NaN,3977,2180370,1,1,1
1324,1324,1324,218138,247516,2012-01-01,F,volleyball,NaN,380,9,...,40928,1,2012-01-26 22:17:00,2013-02-09 16:18:00,NaN,4258,2181380,0,0,0
284,284,284,216834,243463,2012-01-01,F,lacrosse,NaN,179,1,...,0,1,2012-01-08 21:58:00,2012-07-05 22:43:00,NaN,2018,2168340,0,0,0
279,279,279,216741,243503,2012-01-01,F,volleyball,NaN,245,2,...,40914,1,2012-01-09 00:10:00,2012-09-10 15:43:00,NaN,1738,2167410,0,0,0
1279,1279,1279,217939,244779,2012-01-01,F,soccer,NaN,305,2,...,40918,1,2012-01-13 02:22:00,2012-11-13 21:21:00,NaN,3866,2179390,0,0,0
1,1,1,215069,241447,2012-01-01,F,soccer,NaN,851,2,...,40907,1,2012-01-01 16:43:00,2014-05-01 09:52:00,NaN,58,2150690,0,0,0
870,870,870,219223,246243,2012-01-01,F,soccer,NaN,578,1,...,40926,1,2012-01-20 18:57:00,2013-08-20 09:00:00,NaN,5042,2192230,0,0,0
1109,1109,1109,219014,246143,2012-01-01,M,ice_hockey,NaN,101,2,...,40926,1,2012-01-20 01:09:00,2012-04-30 02:15:00,NaN,4986,2190140,0,0,0
4857,4857,4857,226529,256822,2012-02-01,F,soccer,NaN,43,2,...,40959,2,2012-02-28 13:32:00,2012-04-11 19:47:00,NaN,15067,2265291,0,0,0
5371,5371,5371,222808,256048,2012-02-01,M,soccer,NaN,35,1,...,40963,2,2012-02-26 01:31:00,2012-04-01 00:55:00,NaN,8571,2228081,0,0,0
1100,1100,1100,218138,247516,2012-02-01,F,volleyball,NaN,380,0,...,40928,2,2012-01-26 22:17:00,2013-02-09 16:18:00,NaN,4259,2181380,0,0,0
4457,4457,4457,225446,255250,2012-02-01,F,volleyball,NaN,213,7,...,40964,2,2012-02-23 03:48:00,2012-09-23 23:34:00,NaN,13443,2254461,0,0,0
254,254,254,215069,241447,2012-02-01,F,soccer,NaN,851,0,...,40907,2,2012-01-01 16:43:00,2014-05-01 09:52:00,NaN,59,2150690,0,0,0
1860,1860,1860,217939,244779,2012-02-01,F,soccer,NaN,305,0,...,40918,2,2012-01-13 02:22:00,2012-11-13 21:21:00,NaN,3867,2179390,0,0,0

In [82]:
onemchurn[onemchurn.Athlete==219014]

,Unnamed: 0,Unnamed: 0.1,Athlete,Subscription,Month,gender,sport,SegmentName,Duration,EventsAttended,...,ECoachEval_Freq,ECoachImport_Freq,ECoachSearchHit_Freq,ECoachVisit_Freq,Ecolleges_going_to_the_event_Freq,Efailed_subscription_Freq,EEmailsDigest_Freq,Epost_event_email_Freq,Esms_update_Freq,ECCNote_Freq
1109,1109,1109,219014,246143,2012-01-01,M,ice_hockey,NaN,101,2,...,0,0,0,0,0,0,0,0,0,0
3296,3296,3296,219014,246143,2012-02-01,M,ice_hockey,NaN,101,0,...,0,0,0,0,0,0,0,0,0,0
1425,1425,1425,219014,246143,2012-03-01,M,ice_hockey,NaN,101,0,...,0,0,0,0,0,0,0,0,0,0
3183,3183,3183,219014,246143,2012-04-01,M,ice_hockey,NaN,101,0,...,0,0,0,0,0,0,0,0,0,0
1442,1442,1442,219014,880130,2014-05-01,M,ice_hockey,NaN,199,0,...,0,0,2,0,0,0,0,0,0,0
816,816,816,219014,880130,2014-06-01,M,ice_hockey,NaN,199,0,...,0,0,3,0,0,1,0,0,0,0
1461,1461,1461,219014,880130,2014-07-01,M,ice_hockey,NaN,199,0,...,0,0,3,0,0,1,0,0,0,0
1117,1117,1117,219014,880130,2014-08-01,M,ice_hockey,NaN,199,0,...,0,0,4,0,0,1,0,0,0,0
1236,1236,1236,219014,880130,2014-09-01,M,ice_hockey,NaN,199,0,...,0,0,5,0,0,1,0,0,0,1
1462,1462,1462,219014,880130,2014-10-01,M,ice_hockey,NaN,199,0,...,0,0,5,0,0,1,0,0,0,1
1444,1444,1444,219014,1086288,2014-11-01,M,ice_hockey,NaN,214,0,...,0,0,8,0,0,1,0,0,0,1
1118,1118,1118,219014,1086288,2014-12-01,M,ice_hockey,NaN,214,0,...,0,0,8,0,0,1,0,0,0,1
1169,1169,1169,219014,1086288,2015-01-01,M,ice_hockey,NaN,214,0,...,0,0,8,0,0,1,0,0,0,1
2134,2134,2134,219014,1086288,2015-02-01,M,ice_hockey,NaN,214,0,...,0,0,8,0,0,1,0,0,0,1
1426,1426,1426,219014,1086288,2015-03-01,M,ice_hockey,NaN,214,0,...,0,0,8,0,0,1,0,0,0,1
1407,1407,1407,219014,1086288,2015-04-01,M,ice_hockey,NaN,214,0,...,0,0,11,0,0,1,0,0,0,4
1443,1443,1443,219014,1086288,2015-05-01,M,ice_hockey,NaN,214,0,...,0,0,14,0,0,1,0,0,0,4
869,869,869,219014,1086288,2015-06-01,M,ice_hockey,NaN,214,0,...,0,0,17,0,0,1,0,0,0,5
1000,1000,1000,219014,1086288,2015-07-01,M,ice_hockey,NaN,214,0,...,0,0,20,0,0,1,0,0,0,5

In [7]:
len(tmchurn[tmchurn.TMChurn == 1 ])

11734

In [12]:
tmchurn_2014 = tmchurn[tmchurn.NumYear == 2014]

In [14]:
len(tmchurn_2014[tmchurn_2014.TMChurn == 0 ])

57693

In [15]:
len(tmchurn_2014[tmchurn_2014.TMChurn == 1 ])

8581

In [53]:
onemchurn['Month'] = pd.to_datetime(pd.Series(onemchurn['Month']), format='%Y-%m-%d')

In [54]:
onemchurn = onemchurn.sort(['Month'],ascending=[1])

/Users/jamesmwakichako/Documents/Kaggle/kaggle_py/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [19]:
tmchurn_2014 = tmchurn_2014.sort(['Month'], ascending=[True])

/Users/jamesmwakichako/Documents/Kaggle/kaggle_py/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [20]:
tmchurn_2014.head(5)

,Unnamed: 0,Athlete,Subscription,Month,gender,sport,SegmentName,Duration,EventsAttended,EventsAttended_Frequency,...,RecencyStat,AthleteRecordNumber,created_at,updated_at,status,ID,AthleteSub,CaptainU_CHURN,MSG_CHURN,TMChurn
43710,43710,496027,620797,2014-01-01,M,soccer,NaN,594,0,3,...,41668,25,2013-07-08 23:20:00,2015-02-22 14:06:00,NaN,264066,4960271,0,0,0
71041,71041,532107,697135,2014-01-01,F,soccer,NaN,489,0,2,...,41668,25,2013-10-08 19:43:00,2015-02-09 03:11:00,NaN,301810,5321071,0,0,0
35635,35635,346031,698982,2014-01-01,F,softball,NaN,516,0,9,...,41668,25,2013-10-10 10:24:00,2015-03-10 08:58:00,NaN,140922,3460311,0,0,0
50929,50929,372596,427190,2014-01-01,M,soccer,NaN,783,0,13,...,41667,25,2012-11-14 04:16:00,2015-01-06 03:06:00,NaN,168586,3725961,0,0,0
80491,80491,545468,733563,2014-01-01,M,lacrosse,NaN,62,0,5,...,41662,25,2013-11-12 13:16:00,2014-01-13 13:12:00,NaN,325777,5454681,1,1,1

In [56]:
onemchurn.columns.values

array(['Unnamed: 0', 'Unnamed: 0.1', 'Athlete', 'Subscription', 'Month',
       'gender', 'sport', 'SegmentName', 'Duration', 'EventsAttended',
       'EventsAttended_Frequency', 'EventsAttended_LastDate',
       'EventsAttended_Recency', 'Hits', 'Hits_Frequency', 'Hits_LastDate',
       'Hits_Recency', 'Hprofileview', 'Hcoachimport', 'Hmessage',
       'Hsearchhit', 'HNULL', 'Hcoacheval', 'Hvideoview', 'Hemailopen',
       'Emails', 'Emails_Frequency', 'Emails_LastDate', 'Emails_Recency',
       'EAthlete newsletter', 'Eathlete_new', 'Eathlete_new_info_request',
       'ECCNote', 'ECCNote_camp', 'Ecoach_list_known_updated',
       'ECoachEmailOpen', 'ECoachEval', 'ECoachImport', 'ECoachSearchHit',
       'ECoachVideoViewHit', 'ECoachVisit', 'Ecolleges_going_to_the_event',
       'Efailed_subscription', 'Ehighlight_video__regathlete_11',
       'Ehighlight_video__regathlete_2', 'Ehighlight_video__regathlete_4',
       'EEmailsDigest', 'Eparent_new', 'Eparent_welcome',
       'Epost_event_email', 'Esms_update', 'CollegeProspects',
       'CollegeProspects_Frequency', 'CollegeProspects_LastDate',
       'CollegeProspects_Recency', 'MessagesReceived',
       'MessagesReceived_Frequency', 'MessagesReceived_LastDate',
       'MessagesReceived_Recency', 'MessagesSent',
       'MessagesSent_Frequency', 'MessagesSent_LastDate',
       'MessagesSent_Recency', 'Made_Team?', 'DateNum', 'NumYear',
       'NumMonth', 'Subscriber?', 'monthly_price', 'Subscriptions_BOM',
       'Subscription_Started', 'subscription_Ended', 'Subscriptions_EOM',
       'RecencyNow', 'RecencyStat', 'AthleteRecordNumber', 'created_at',
       'updated_at', 'status', 'ID', 'AthleteSub', 'CaptainU_CHURN',
       'MSG_CHURN', 'TMChurn'], dtype=object)

In [57]:
onemchurn.shape

(133394, 84)

In [21]:
onemchurn['Hit_Frequency']=onemchurn.groupby(['Athlete'],axis=0).Hits.cumsum()

In [58]:
onemchurn['Hprofileview_Freq']=onemchurn.groupby(['Athlete'],axis=0).Hprofileview.cumsum()

In [59]:
onemchurn['Hcoachimport_Freq']=onemchurn.groupby(['Athlete'],axis=0).Hcoachimport.cumsum()

In [60]:
onemchurn['Hmessage_Freq']=onemchurn.groupby(['Athlete'],axis=0).Hmessage.cumsum()

In [61]:
onemchurn['Hsearchhit_Freq']=onemchurn.groupby(['Athlete'],axis=0).Hsearchhit.cumsum()

In [62]:
onemchurn['Hcoacheval_Freq']=onemchurn.groupby(['Athlete'],axis=0).Hcoacheval.cumsum()

In [63]:
onemchurn['Hemailopen_Freq']=onemchurn.groupby(['Athlete'],axis=0).Hemailopen.cumsum()

In [64]:
onemchurn['Eathlete_new_info_request_Freq']=onemchurn.groupby(['Athlete'],axis=0).Eathlete_new_info_request.cumsum()

In [65]:
onemchurn['Ecoach_list_known_updated_Freq']=onemchurn.groupby(['Athlete'],axis=0).Ecoach_list_known_updated.cumsum()

In [66]:
onemchurn['ECoachEmailOpen_Freq']=onemchurn.groupby(['Athlete'],axis=0).ECoachEmailOpen.cumsum()

In [67]:
onemchurn['ECoachEval_Freq']=onemchurn.groupby(['Athlete'],axis=0).ECoachEval.cumsum()

In [68]:
onemchurn['ECoachImport_Freq']=onemchurn.groupby(['Athlete'],axis=0).ECoachImport.cumsum()

In [69]:
onemchurn['ECoachSearchHit_Freq']=onemchurn.groupby(['Athlete'],axis=0).ECoachSearchHit.cumsum()

In [70]:
onemchurn['ECoachVisit_Freq']=onemchurn.groupby(['Athlete'],axis=0).ECoachVisit.cumsum()

In [71]:
onemchurn['Ecolleges_going_to_the_event_Freq']=onemchurn.groupby(['Athlete'],axis=0).Ecolleges_going_to_the_event.cumsum()

In [72]:
onemchurn['Efailed_subscription_Freq']=onemchurn.groupby(['Athlete'],axis=0).Efailed_subscription.cumsum()

In [73]:
onemchurn['EEmailsDigest_Freq']=onemchurn.groupby(['Athlete'],axis=0).EEmailsDigest.cumsum()

In [74]:
onemchurn['Epost_event_email_Freq']=onemchurn.groupby(['Athlete'],axis=0).Epost_event_email.cumsum()

In [75]:
onemchurn['Esms_update_Freq']=onemchurn.groupby(['Athlete'],axis=0).Esms_update.cumsum()

In [76]:
onemchurn['ECCNote_Freq']=onemchurn.groupby(['Athlete'],axis=0).ECCNote.cumsum()

In [77]:
onemchurn.shape

(133394, 103)

In [78]:
onemchurn.head(5)

,Unnamed: 0,Unnamed: 0.1,Athlete,Subscription,Month,gender,sport,SegmentName,Duration,EventsAttended,...,ECoachEval_Freq,ECoachImport_Freq,ECoachSearchHit_Freq,ECoachVisit_Freq,Ecolleges_going_to_the_event_Freq,Efailed_subscription_Freq,EEmailsDigest_Freq,Epost_event_email_Freq,Esms_update_Freq,ECCNote_Freq
3188,3188,3188,220000,247241,2012-01-01,F,volleyball,NaN,83,0,...,0,0,0,0,0,0,0,0,0,0
1322,1322,1322,218037,245146,2012-01-01,F,lacrosse,NaN,15,1,...,0,0,0,0,0,0,0,0,0,0
1324,1324,1324,218138,247516,2012-01-01,F,volleyball,NaN,380,9,...,0,0,0,0,0,0,0,0,0,0
284,284,284,216834,243463,2012-01-01,F,lacrosse,NaN,179,1,...,0,0,0,0,0,0,0,0,0,0
279,279,279,216741,243503,2012-01-01,F,volleyball,NaN,245,2,...,0,0,0,0,0,0,0,0,0,0

In [83]:
onemchurn['Month'].dtype

dtype('<M8[ns]')

In [84]:
onemchurn.to_csv('data/onemchurn_freq.csv', encoding='utf-8')

In [45]:
len(tmchurn_2014[tmchurn_2014.NumMonth==3])

4360

In [44]:
tmchurn_2014.to_csv('data/TMChurn_2014.csv', encoding='utf-8')

In [30]:
training.to_csv('data/training_Freq.csv', encoding='utf-8')

In [60]:
active = pd.read_csv('data/active.csv')

In [63]:
active.shape

(16117, 102)

In [62]:
active.columns.values

array(['Unnamed: 0', 'Athlete', 'Subscription', 'Month', 'gender', 'sport',
       'Duration', 'EventsAttended', 'EventsAttended_Frequency',
       'EventsAttended_LastDate', 'Hits', 'Hits_Frequency',
       'Hits_LastDate', 'Hits_Recency', 'Hprofileview', 'Hcoachimport',
       'Hmessage', 'Hsearchhit', 'HNULL', 'Hcoacheval', 'Hvideoview',
       'Hemailopen', 'Emails', 'Emails_Frequency', 'Emails_LastDate',
       'Emails_Recency', 'EAthlete newsletter', 'Eathlete_new',
       'Eathlete_new_info_request', 'ECCNote', 'ECCNote_camp',
       'Ecoach_list_known_updated', 'ECoachEmailOpen', 'ECoachEval',
       'ECoachImport', 'ECoachSearchHit', 'ECoachVideoViewHit',
       'ECoachVisit', 'Ecolleges_going_to_the_event',
       'Efailed_subscription', 'Ehighlight_video__regathlete_11',
       'Ehighlight_video__regathlete_2', 'Ehighlight_video__regathlete_4',
       'EEmailsDigest', 'Eparent_new', 'Eparent_welcome',
       'Epost_event_email', 'Esms_update', 'CollegeProspects',
       'CollegeProspects_Frequency', 'CollegeProspects_LastDate',
       'CollegeProspects_Recency', 'MessagesReceived',
       'MessagesReceived_Frequency', 'MessagesReceived_LastDate',
       'MessagesReceived_Recency', 'MessagesSent',
       'MessagesSent_Frequency', 'MessagesSent_LastDate',
       'MessagesSent_Recency', 'CaptainU_CHURN', 'MSG_CHURN', 'Made_Team?',
       'DateNum', 'NumYear', 'NumMonth', 'Subscriber?', 'monthly_price',
       'Subscriptions_BOM', 'Subscription_Started', 'subscription_Ended',
       'Subscriptions_EOM', 'RecencyNow', 'RecencyStat',
       'AthleteRecordNumber', 'created_at', 'updated_at', 'status', 'ID',
       'AthleteSub', 'Hit_Frequency_Pandas', 'Hprofileview_Freq',
       'Hcoachimport_Freq', 'Hmessage_Freq', 'Hsearchhit_Freq',
       'Hcoacheval_Freq', 'Hemailopen_Freq',
       'Eathlete_new_info_request_Freq', 'Ecoach_list_known_updated_Freq',
       'ECoachEmailOpen_Freq', 'ECoachEval_Freq', 'ECoachImport_Freq',
       'ECoachSearchHit_Freq', 'ECoachVisit_Freq',
       'Ecolleges_going_to_the_event_Freq', 'Efailed_subscription_Freq',
       'EEmailsDigest_Freq', 'Epost_event_email_Freq', 'Esms_update_Freq',
       'ID.1', 'Athlete.1', 'Subscription.1'], dtype=object)